import Foundation

public enum SharedConstants {
    public static let appGroupId = "group.com.jon2g.tiktokstreaksaver"
    public static let cookiesFileName = "cookies.json"
    public static let friendsListFileName = "friends_list.json"
    public static let authRequiredKey = "auth_required"
    public static let friendsListKey = "friends_list"
    public static let messageTextKey = "message_text"
    public static let runHistoryKey = "run_history"
    public static let lastRunKey = "last_run"
    public static let randomizeMessagesKey = "randomize_normal_messages"
    public static let skipUnreachableKey = "skip_unreachable_users"
    public static let loginUserAgentKey = "session_login_ua"
    public static let forceManualRunKey = "force_manual_run"
    public static let lastRunFailureReasonKey = "last_run_failure_reason"
    public static let runLogsFileName = "run_logs.txt"
    public static let messageTextFileName = "message_text.txt"
    public static let randomizeMessagesFlagFileName = "randomize_normal_messages.bool"
    public static let messagesUrl = "https://www.tiktok.com/messages?lang=en"
    public static let defaultMessage = "Hey! Keeping our streak alive! 🔥"
    public static let failureNoNetwork = "no_network"
    public static let failureNoCookies = "no_cookies"
    public static let failureLoginRequired = "login_required"
    public static let failureSendError = "send_error"
    public static let failureScriptMissing = "script_missing"
    public static let failureNavigationFailed = "navigation_failed"
    public static let failureTimedOut = "timed_out"
    public static let failureNoFriendsDue = "no_friends_due"
}
